---
name: example
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install akoi
        uses: suzuki-shunsuke/akoi-install-action@413e8d2f0f1c66d5b05ce3e51dac6a0714124254
      - run: .akoi/bin/akoi --version

      - name: Install akoi version v2.2.0
        uses: suzuki-shunsuke/akoi-install-action@413e8d2f0f1c66d5b05ce3e51dac6a0714124254
        with:
          version: 'v2.2.0'
      - run: .akoi/bin/akoi --version

      - name: Install akoi on dist/akoi
        uses: suzuki-shunsuke/akoi-install-action@413e8d2f0f1c66d5b05ce3e51dac6a0714124254
        with:
          path: dist/akoi
      - run: dist/akoi --version

      - name: Install akoi on dist/akoi version 2.2.0
        uses: suzuki-shunsuke/akoi-install-action@413e8d2f0f1c66d5b05ce3e51dac6a0714124254
        with:
          version: 'v2.2.0'
          path: dist/akoi
      - run: dist/akoi --version
